name: Build/release

on: push

env:
  SNAPCRAFT_BUILD_ENVIRONMENT: host

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-18.04, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 17
      
      - name: Install deps
        run: npm ci

      - name: Install Snapcraft
        run: sudo snap install snapcraft --classic
        if: runner.os == 'Linux'

      - name: Build
        run: npm run make

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: out/make/*